Attempted fixes
This pipeline fails with:

    Command: kubectl config use-context
    gitops-test.cloud-platform.service.justice.gov.uk failed.
    error: no context exists with the name:
    "gitops-test.cloud-platform.service.justice.gov.uk".

Try to fix this by:

* Using the 'concourse' version of the tools image
* remove the KUBECONFIG_AWS_ACCESS_KEY_ID and
KUBECONFIG_AWS_SECRET_ACCESS_KEY (since the build pipeline doesn't set
those)